<div class="container">
    <h2 class="text-center">Inicio Sesion</h2>
    <?= Form::open('index/ingresar') ?>
    <div class="mb-3">
        <?= Form::label('Usuario','usuario_email',['class'=>'form-label'] ) ?>
        <?= Form::email('usuario.email',['class'=>'form-control'] ) ?>
    </div>
    <div class="mb-3">
        <?= Form::label('Password','usuario_password',['class'=>'form-label']) ?>
        <?= Form::password('usuario.password',['class'=>'form-control']) ?>
    </div>
    <div class="mb-3">
    <?= Form::submit('ingresar',['class'=>'btn btn-primary']) ?>
    </div>
</div>
